# ==========================================================
# BANCO 3 - PostgreSQL Client Authentication Configuration
# Ubicacion en nodo DB01: /data/postgresql/pg_hba.conf
# Estado: Verificado en vivo
# Politica: Acceso remoto restringido exclusivamente a WEB01 (172.16.2.2/32)
# ==========================================================

# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

# Regla de acceso para la capa de aplicacion Web:
host    all             all             172.16.2.2/32           scram-sha-256
